ALL_LEVELS = [
    // TestLevel,
    // TutorialPedal,
    // TutorialFlips,
    // TutorialJumps,
    TutorialStomp,
    TutorialWheelies,
    LevelFrontflip,
    LevelBackflipFrontflip,
    LevelWheelieBasics,
    LevelFrontflipWheelie,
    LevelDoubleTricks,
    LevelAdvancedCombos,
    LevelFinale,
];
