SONG = {
  "rowLen": 5513,
  "endPattern": 8,
  "songData": [
    {
      "osc1_oct": 6,
      "osc1_det": 0,
      "osc1_detune": 0,
      "osc1_xenv": 0,
      "osc1_vol": 180,
      "osc1_waveform": 0,
      "osc2_oct": 7,
      "osc2_det": 0,
      "osc2_detune": 6,
      "osc2_xenv": 0,
      "osc2_vol": 60,
      "osc2_waveform": 1,
      "noise_fader": 220,
      "env_attack": 10,
      "env_sustain": 120,
      "env_release": 300,
      "env_master": 192,
      "fx_filter": 2,
      "fx_freq": 8000,
      "fx_resonance": 120,
      "fx_delay_time": 4,
      "fx_delay_amt": 12,
      "fx_pan_freq": 2,
      "fx_pan_amt": 20,
      "lfo_osc1_freq": 0,
      "lfo_fx_freq": 0,
      "lfo_freq": 0,
      "lfo_amt": 0,
      "lfo_waveform": 0,
      "p": [
        1,
        2,
        1,
        3,
        1,
        2,
        4,
        3
      ],
      "c": [
        {
          "n": [
            111,
            0,
            0,
            0,
            141,
            0,
            0,
            0,
            126,
            0,
            0,
            0,
            141,
            0,
            0,
            0,
            111,
            0,
            0,
            0,
            141,
            0,
            111,
            0,
            126,
            0,
            0,
            0,
            141,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            111,
            0,
            141,
            0,
            141,
            0,
            141,
            0,
            126,
            0,
            141,
            0,
            141,
            0,
            141,
            0,
            111,
            0,
            141,
            0,
            141,
            0,
            111,
            0,
            126,
            0,
            141,
            0,
            141,
            0,
            141,
            0
          ]
        },
        {
          "n": [
            111,
            0,
            0,
            0,
            141,
            0,
            0,
            0,
            126,
            0,
            0,
            0,
            141,
            0,
            0,
            0,
            111,
            0,
            0,
            0,
            141,
            0,
            0,
            0,
            126,
            0,
            126,
            0,
            126,
            0,
            126,
            0
          ]
        },
        {
          "n": [
            111,
            0,
            141,
            0,
            126,
            0,
            141,
            0,
            111,
            0,
            141,
            0,
            111,
            0,
            141,
            0,
            126,
            0,
            141,
            0,
            111,
            0,
            141,
            0
          ]
        }
      ]
    },
    {
      "osc1_oct": 7,
      "osc1_det": 0,
      "osc1_detune": 7,
      "osc1_xenv": 0,
      "osc1_vol": 200,
      "osc1_waveform": 2,
      "osc2_oct": 7,
      "osc2_det": 0,
      "osc2_detune": 13,
      "osc2_xenv": 0,
      "osc2_vol": 180,
      "osc2_waveform": 2,
      "noise_fader": 0,
      "env_attack": 50,
      "env_sustain": 1100,
      "env_release": 900,
      "env_master": 191,
      "fx_filter": 1,
      "fx_freq": 1400,
      "fx_resonance": 120,
      "fx_delay_time": 6,
      "fx_delay_amt": 90,
      "fx_pan_freq": 4,
      "fx_pan_amt": 100,
      "lfo_osc1_freq": 0,
      "lfo_fx_freq": 1,
      "lfo_freq": 4,
      "lfo_amt": 30,
      "lfo_waveform": 0,
      "p": [
        1,
        2,
        3,
        1,
        2,
        3,
        4,
        1
      ],
      "c": [
        {
          "n": [
            151,
            0,
            0,
            0,
            154,
            0,
            0,
            0,
            146,
            0,
            0,
            0,
            149,
            0,
            0,
            0,
            151,
            0,
            0,
            0,
            154,
            0,
            0,
            0,
            158,
            0,
            0,
            0,
            149,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            151,
            0,
            153,
            0,
            154,
            0,
            156,
            0,
            154,
            0,
            153,
            0,
            151,
            0,
            149,
            0,
            151,
            0,
            0,
            0,
            154,
            0,
            0,
            0,
            158,
            0,
            0,
            0,
            156,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            0,
            0,
            151,
            0,
            0,
            0,
            154,
            0,
            0,
            0,
            146,
            0,
            0,
            0,
            149,
            0,
            0,
            0,
            151,
            0,
            0,
            0,
            154,
            0,
            158,
            0,
            0,
            0,
            156,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            151,
            0,
            154,
            0,
            158,
            0,
            161,
            0,
            159,
            0,
            158,
            0,
            156,
            0,
            154,
            0,
            153,
            0,
            151,
            0,
            149,
            0,
            146,
            0,
            144,
            0,
            0,
            0,
            146,
            0,
            147,
            0
          ]
        }
      ]
    },
    {
      "osc1_oct": 7,
      "osc1_det": 0,
      "osc1_detune": 3,
      "osc1_xenv": 0,
      "osc1_vol": 180,
      "osc1_waveform": 1,
      "osc2_oct": 7,
      "osc2_det": 0,
      "osc2_detune": 9,
      "osc2_xenv": 0,
      "osc2_vol": 120,
      "osc2_waveform": 1,
      "noise_fader": 0,
      "env_attack": 10,
      "env_sustain": 380,
      "env_release": 520,
      "env_master": 185,
      "fx_filter": 2,
      "fx_freq": 2200,
      "fx_resonance": 100,
      "fx_delay_time": 6,
      "fx_delay_amt": 120,
      "fx_pan_freq": 6,
      "fx_pan_amt": 120,
      "lfo_osc1_freq": 0,
      "lfo_fx_freq": 1,
      "lfo_freq": 5,
      "lfo_amt": 22,
      "lfo_waveform": 0,
      "p": [
        1,
        2,
        1,
        3,
        2,
        1,
        4,
        3
      ],
      "c": [
        {
          "n": [
            0,
            0,
            146,
            0,
            0,
            0,
            149,
            0,
            0,
            0,
            151,
            0,
            0,
            0,
            142,
            0,
            0,
            0,
            146,
            0,
            0,
            0,
            149,
            0,
            0,
            0,
            151,
            0,
            0,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            142,
            0,
            0,
            0,
            144,
            0,
            0,
            0,
            146,
            0,
            0,
            0,
            144,
            0,
            0,
            0,
            142,
            0,
            0,
            0,
            141,
            0,
            0,
            0,
            139,
            0,
            0,
            0,
            137,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            0,
            0,
            139,
            0,
            0,
            0,
            142,
            0,
            146,
            0,
            0,
            0,
            144,
            0,
            0,
            0,
            0,
            0,
            142,
            0,
            0,
            0,
            146,
            0,
            0,
            0,
            149,
            0,
            0,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            139,
            0,
            0,
            0,
            142,
            0,
            0,
            0,
            146,
            0,
            0,
            0,
            149,
            0,
            0,
            0,
            147,
            0,
            146,
            0,
            144,
            0,
            142,
            0,
            141,
            0,
            139,
            0,
            0,
            0,
            0,
            0
          ]
        }
      ]
    },
    {
      "osc1_oct": 6,
      "osc1_det": 0,
      "osc1_detune": 0,
      "osc1_xenv": 0,
      "osc1_vol": 200,
      "osc1_waveform": 1,
      "osc2_oct": 6,
      "osc2_det": 0,
      "osc2_detune": 4,
      "osc2_xenv": 0,
      "osc2_vol": 90,
      "osc2_waveform": 0,
      "noise_fader": 0,
      "env_attack": 5,
      "env_sustain": 700,
      "env_release": 600,
      "env_master": 192,
      "fx_filter": 1,
      "fx_freq": 600,
      "fx_resonance": 90,
      "fx_delay_time": 3,
      "fx_delay_amt": 0,
      "fx_pan_freq": 0,
      "fx_pan_amt": 0,
      "lfo_osc1_freq": 0,
      "lfo_fx_freq": 0,
      "lfo_freq": 4,
      "lfo_amt": 9,
      "lfo_waveform": 0,
      "p": [
        1,
        2,
        1,
        3,
        1,
        2,
        4,
        1
      ],
      "c": [
        {
          "n": [
            115,
            0,
            0,
            0,
            115,
            0,
            0,
            0,
            115,
            0,
            0,
            0,
            115,
            0,
            0,
            0,
            115,
            0,
            110,
            0,
            115,
            0,
            0,
            0,
            113,
            0,
            0,
            0,
            115,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            115,
            0,
            0,
            0,
            118,
            0,
            0,
            0,
            110,
            0,
            0,
            0,
            113,
            0,
            0,
            0,
            115,
            0,
            0,
            0,
            118,
            0,
            0,
            0,
            110,
            0,
            0,
            0,
            113,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            0,
            0,
            115,
            0,
            0,
            0,
            0,
            0,
            118,
            0,
            0,
            0,
            110,
            0,
            0,
            0,
            0,
            0,
            113,
            0,
            0,
            0,
            0,
            0,
            127,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            115,
            0,
            118,
            0,
            122,
            0,
            0,
            0,
            125,
            0,
            0,
            0,
            123,
            0,
            122,
            0,
            120,
            0,
            0,
            0,
            118,
            0,
            0,
            0,
            117,
            0,
            0,
            0,
            115,
            0,
            0,
            0
          ]
        }
      ]
    },
    {
      "osc1_oct": 7,
      "osc1_det": 0,
      "osc1_detune": 0,
      "osc1_xenv": 0,
      "osc1_vol": 170,
      "osc1_waveform": 2,
      "osc2_oct": 7,
      "osc2_det": 0,
      "osc2_detune": 10,
      "osc2_xenv": 0,
      "osc2_vol": 150,
      "osc2_waveform": 3,
      "noise_fader": 40,
      "env_attack": 5,
      "env_sustain": 300,
      "env_release": 900,
      "env_master": 185,
      "fx_filter": 2,
      "fx_freq": 3500,
      "fx_resonance": 110,
      "fx_delay_time": 6,
      "fx_delay_amt": 85,
      "fx_pan_freq": 5,
      "fx_pan_amt": 150,
      "lfo_osc1_freq": 0,
      "lfo_fx_freq": 1,
      "lfo_freq": 4,
      "lfo_amt": 28,
      "lfo_waveform": 0,
      "p": [
        1,
        2,
        1,
        3,
        1,
        2,
        4,
        1
      ],
      "c": [
        {
          "n": [
            0,
            0,
            151,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            154,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            158,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            161,
            0,
            0,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            139,
            0,
            0,
            0,
            141,
            0,
            0,
            0,
            142,
            0,
            0,
            0,
            144,
            0,
            0,
            0,
            146,
            0,
            0,
            0,
            147,
            0,
            0,
            0,
            149,
            0,
            0,
            0,
            151,
            0,
            0,
            0
          ]
        },
        {
          "n": [
            151,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            154,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            158,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            149,
            0,
            151,
            0,
            154,
            0,
            158,
            0
          ]
        },
        {
          "n": [
            163,
            0,
            161,
            0,
            159,
            0,
            158,
            0,
            156,
            0,
            154,
            0,
            153,
            0,
            151,
            0,
            149,
            0,
            147,
            0,
            146,
            0,
            144,
            0,
            142,
            0,
            141,
            0,
            139,
            0,
            0,
            0
          ]
        }
      ]
    }
  ],
  "songLen": 8
}

playSong = () => new MusicGenerator(SONG).createAudioBuffer(buffer => {
    const source = audioCtx.createBufferSource();
    source.buffer = buffer;
    source.loop = true;

    const gainNode = audioCtx.createGain();
    gainNode.connect(audioCtx.destination);
    source.connect(gainNode);
    source.nomangle(start)();

    playSong = () => 0; // Prevent playing the song again
    setSongVolume = (x) => gainNode.gain.value = x * SONG_VOLUME;
    setSongVolume(1);
});

setSongVolume = () => 0;
